Generating rda file with version 2
version 3 (default) is causing problems in deployment

```
Warning: file 'holidaysB3.rda' has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package 'bizdays'
```